version: 2
updates:
  # Frontend dependencies (React application)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    assignees:
      - "mbuckingham74"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "frontend"

  # Backend dependencies (Express API)
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    assignees:
      - "mbuckingham74"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "backend"

  # GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    assignees:
      - "mbuckingham74"
    commit-message:
      prefix: "ci"
    labels:
      - "dependencies"
      - "ci/cd"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    assignees:
      - "mbuckingham74"
    commit-message:
      prefix: "chore"
    labels:
      - "dependencies"
      - "docker"
