# Gitleaks Configuration for Meteo Weather App
# Prevents accidental commits of secrets, API keys, passwords, and tokens

title = "Gitleaks Configuration for Meteo Weather App"

# Extend default gitleaks config
[extend]
useDefault = true

# Allowlist - Files and paths that are safe to ignore
[allowlist]
description = "Allowlisted files and patterns"

# Allow example files (these contain placeholder values, not real secrets)
paths = [
  '''\.env\.example$''',
  '''\.env\..*\.example$''',
  '''README\.md$''',
  '''CLAUDE\.md$''',
  '''QUICKSTART\.md$''',
  '''DEPLOYMENT.*\.md$''',
  '''SECURITY.*\.md$''',
  '''^docs/.*\.md$''',
]

# Allow specific patterns that look like secrets but aren't
regexes = [
  # Allow example/placeholder API keys in documentation
  '''your_api_key_here''',
  '''your_secret_here''',
  '''example_key''',
  '''placeholder''',

  # Allow short hex strings (build hashes, not secrets) - max 8 chars
  '''[a-f0-9]{8}''',
]

# Allow specific commits (if needed for historical reasons)
# commits = [
#   "commit-hash-to-allow",
# ]

# Custom rules for this project
[[rules]]
id = "openweather-api-key"
description = "OpenWeather API Key"
regex = '''(?i)(openweather[_-]?api[_-]?key|OPENWEATHER_API_KEY)\s*[:=]\s*["']?([a-f0-9]{32})["']?'''
tags = ["key", "openweather"]

[[rules]]
id = "visual-crossing-api-key"
description = "Visual Crossing API Key"
regex = '''(?i)(visual[_-]?crossing[_-]?api[_-]?key|VISUAL_CROSSING_API_KEY)\s*[:=]\s*["']?([A-Z0-9]{25})["']?'''
tags = ["key", "visualcrossing"]

[[rules]]
id = "anthropic-api-key"
description = "Anthropic Claude API Key"
regex = '''(?i)(anthropic[_-]?api[_-]?key|METEO_ANTHROPIC_API_KEY|ANTHROPIC_API_KEY)\s*[:=]\s*["']?(sk-ant-api03-[a-zA-Z0-9_-]{95})["']?'''
tags = ["key", "anthropic", "claude"]

[[rules]]
id = "jwt-secret"
description = "JWT Secret Key"
regex = '''(?i)(jwt[_-]?secret|JWT_SECRET|JWT_REFRESH_SECRET)\s*[:=]\s*["']?([a-zA-Z0-9_-]{32,})["']?'''
tags = ["secret", "jwt"]

[[rules]]
id = "database-password"
description = "Database Password"
regex = '''(?i)(db[_-]?password|DB_PASSWORD|DB_ROOT_PASSWORD)\s*[:=]\s*["']?([^\s"']+)["']?'''
tags = ["password", "database"]

[[rules]]
id = "generic-api-key"
description = "Generic API Key Pattern"
regex = '''(?i)api[_-]?key\s*[:=]\s*["']?([a-z0-9]{32,})["']?'''
tags = ["key", "api"]

# Entropy-based detection for high-entropy strings (potential secrets)
[[rules]]
id = "high-entropy-string"
description = "High Entropy String (Potential Secret)"
regex = '''[a-zA-Z0-9+/]{40,}'''
entropy = 4.5
tags = ["entropy", "secret"]
