name: ❓ Question
description: Ask a question about using or deploying Meteo Weather App
title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your question! Please provide as much detail as possible.

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: How do I...?
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What is your question about?
      options:
        - Installation/Setup
        - Configuration
        - API Keys
        - Docker/Deployment
        - Features/Usage
        - Troubleshooting
        - Development
        - Contributing
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context or what you've already tried
      placeholder: I'm trying to... I've already looked at...
    validations:
      required: false

  - type: input
    id: deployment
    attributes:
      label: Deployment Type
      description: How are you running the app?
      placeholder: e.g., Docker Compose, Local, VPS, etc.
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any other information that might be helpful
      placeholder: Any other details...

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have checked the README and documentation
          required: true
        - label: I have searched existing issues for similar questions
          required: true
